- hosts: webgroup
  remote_user: demo
  become: true
  gather_facts: false
  pre_tasks:
  - setup: # aka gather_facts
  - name: Add domain to CloudFalre
    cloudflare_dns:
      zone: "{{base_web_domain}}"
      record: "*.{{ansible_nodename}}"
      type: A
      value: "{{ ansible_default_ipv4.address }}"
      account_email: "{{ certbot_cloudflare_email }}"
      account_api_token: "{{ certbot_cloudflare_api_key }}"
    register: record
  - debug: var=record
  - name: set timezone to America/Chicago
    timezone:
      name: America/Chicago
  - name: gather os specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_distribution }}-{{ php_version }}.yml"
      - "{{ ansible_distribution }}.yml"
    tags: vars
  vars_files:
    - vars/webgroup.yml
    - vars/main-vars.yml

  roles:
    - users
    - geerlingguy.git
    - andrewrothstein.hub
    - geerlingguy.postfix
    - role: oefenweb.swapfile
      check_mode: no
    - setup
    - michaelpporter.certbot_cloudflare
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - geerlingguy.composer
    - geerlingguy.php-mysql
    - geerlingguy.mysql
    - geerlingguy.adminer
    - geerlingguy.drush
    - geerlingguy.nodejs
    - sbaerlocher.wp-cli
    - wtanaka.jq
    - logwatch
    - config
