---
  - name: Get software for apt repository management.
    apt: name={{ item }} state=present
    with_items:
      - logwatch

  - name: Add MailTo for logwatch
    lineinfile:
      dest: /usr/share/logwatch/default.conf/logwatch.conf
      state: present
      regexp: '^MailTo'
      line: "MailTo = {{ logwatch_send_to }}"
  - name: Add Mail From for logwatch
    lineinfile:
      dest: /usr/share/logwatch/default.conf/logwatch.conf
      state: present
      regexp: '^MailFrom'
      line: "MailFrom = {{ logwatch_send_from }}"
