---
# tasks file for users
  - import_tasks: sudouser.yml
  - import_tasks: git.yml
    when: "'webgroup' in group_names"

  - name: Disallow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PermitRootLogin"
                line="PermitRootLogin no"
                state=present
    notify: restart sshd

  - name: Setup alternate SSH port
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^Port"
                line="Port {{remote_port}}"
                state=present
    notify: restart sshd

