---
# tasks file for config

- import_tasks: terminus.yml
  when: config_terminus_ci
- import_tasks: gmail.yml
  when: config_postfix_use_gmail

- name: Copy scripts.sh
  copy:
    src: files/scripts.sh
    dest: /etc/profile.d/scripts.sh
    owner: root
    group: root
    mode: 0644

- name: Make sure we can use htpasswd module
  apt: "pkg=python-passlib state=present"
- name: Apache AddDefaultCharset utf-8
  lineinfile:
    dest: /etc/apache2/conf-available/charset.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^AddDefaultCharset', line: 'AddDefaultCharset utf-8' }
  notify: restart apache
- htpasswd:
    path: /etc/apache2/passwdfile
    name: "{{config_htaccess_user}}"
    password: "{{config_htaccess_pass}}"
    owner: root
    group: www-data
    mode: 0640

# phpcs
- name: Install Drupal Coder
  git:
    repo: 'http://git.drupal.org/project/coder.git'
    dest: /var/lib/coder
    version: 8.x-2.x
- name: Install Wordpress coding standards
  git:
    repo: 'https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git'
    dest: /var/lib/wpcs
    version: master
- name: Add Drupal and Wordpress to phpcs
  command: /home/git/.composer/vendor/bin/phpcs --config-set installed_paths /var/lib/coder/coder_sniffer,/var/lib/wpcs
  changed_when: False


- name: Retrieve stuff from mysql
  command: >
    mysql --user=root INFORMATION_SCHEMA
    --execute="SET GLOBAL show_compatibility_56 = ON;"
  register: stuff
  check_mode: False
  changed_when: False

- name: Do something with stuff
  debug: "{{ item }}"
  with_items: stuff.stdout_lines

- name: Remove ONLY_FULL_GROUP_BY from MySQL
  command: >
    mysql --execute="SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));"
  register: stuff
  changed_when: False
- name: Config mySQL
  lineinfile:
    dest: /etc/mysql/my.cnf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items:
    - { regexp: '^!includedir', line: '!includedir /etc/mysql/conf.d/' }
  notify: restart mysql



