---
# tasks file for setup

  - name: Create Local Scripts folder
    file:
      path: /usr/local/scripts
      state: directory
      mode: 0775
  - name: Copy Local Scripts
    copy:
      src: "{{ item }}"
      dest: /usr/local/scripts/
      owner: root
      mode: 0755
    with_fileglob:
      - files/scripts/*

  - name: Copy Local Scripts
    copy:
      src: "{{ item }}"
      dest: /usr/local/bin/
      owner: root
      mode: 0755
    with_fileglob:
      - files/bin/*

  - name: Config Template
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{user_sudouser_username}}"
      group: www-data
      mode: 0755
    with_items:
      - { src: 'files/templates/config.j2', dest: '/usr/local/scripts/config.sh' }

  - name: Get software for apt repository management.
    apt: name={{ item }} state=present
    with_items: "{{ setup_apt_install }}"

  - name: Install iTerm shell intergration
    get_url:
      url: https://iterm2.com/misc/install_shell_integration.sh
      dest: /usr/bin/iterm2
      mode: 0755

  - name: Create Jenkins-sites
    file:
      path: /var/jenkins-sites
      owner: git
      group: www-data
      state: directory
      mode: 0775
  - name: Create Jenkins folder
    file:
      path: /var/jenkins
      owner: git
      group: www-data
      state: directory
      mode: 0775
  - name: Create build folder
    file:
      path: /var/build
      owner: git
      group: www-data
      state: directory
      mode: 0775

  - name: Create hthelpers folder
    file:
      path: /var/hthelpers
      state: directory
      mode: 0775
  - name: Copy hthelpers Scripts
    copy:
      src: "{{ item }}"
      dest: /var/hthelpers
      owner: root
      group: root
      mode: 644
    with_fileglob:
      - files/hthelpers/*

  - name: Create Local Hosting folder
    file:
      path: /var/www/sites/web
      owner: git
      group: www-data
      state: directory
      mode: 0775

  - name: Web Server Templates
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{user_sudouser_username}}"
      group: www-data
      mode: 0755
    with_items:
      - { src: 'files/web/index.php.j2', dest: '/var/www/sites/web/index.php' }
      - { src: 'files/web/phpinfo.php.j2', dest: '/var/www/sites/web/phpinfo.php' }

  - name: web File Templates
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{user_sudouser_username}}"
      group: www-data
      mode: 0755
    with_items:
      - { src: 'files/web/beanstalk-cleanup.php.j2', dest: '/var/www/sites/web/beanstalk-cleanup.php' }
      - { src: 'files/web/cleanupjenkins.php.j2', dest: '/var/www/sites/web/cleanupjenkins.php' }
      - { src: 'files/web/github-check.php.j2', dest: '/var/www/sites/web/github-check.php' }
      - { src: 'files/web/github-log.php.j2', dest: '/var/www/sites/web/github-log.php' }
      - { src: 'files/web/github-pr.php.j2', dest: '/var/www/sites/web/github-pr.php' }
      - { src: 'files/web/github.php.j2', dest: '/var/www/sites/web/github.php' }
      - { src: 'files/web/slack.php.j2', dest: '/var/www/sites/web/slack.php' }
    when: "'webgroup' in group_names"

  - name: Clean html folder
    file:
      state: absent
      path: "/var/www/html/"

  - name: Usage Script
    template:
      src: files/usage.j2
      dest: /usr/local/bin/usage.sh
      owner: root
      group: root
      mode: 0755
  - cron:
      name: "Write Usage"
      minute: "*/15"
      hour: "*"
      job: "/usr/local/bin/usage.sh > /dev/null"

  - name: Sites Script
    template:
      src: files/sites.j2
      dest: /usr/local/bin/sites.sh
      owner: root
      group: root
      mode: 0755
  - cron:
      name: "Write Sites"
      minute: "*/15"
      hour: "*"
      job: "/usr/local/bin/sites.sh > /dev/null"
